services:
  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    environment:
      # Base de datos
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "nextclouddb"
      # Archivos y cache
      PHP_UPLOAD_LIMIT: "16G"
      REDIS_HOST: "nextcloudredis"
      # Servidor SMTP
      SMTP_HOST: "smtp.ucr.ac.cr"
      SMTP_SECURE: "ssl"
      SMTP_PORT: "465"
      SMTP_NAME: "${SMTP_NAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      MAIL_FROM_ADDRESS: "${SMTP_NAME}"
      MAIL_DOMAIN: "ucr.ac.cr"
      # Proxy
      APACHE_DISABLE_REWRITE_IP: "1"
      TRUSTED_PROXIES: "${TRUSTED_PROXIES}"
      OVERWRITEHOST: "${OVERWRITEHOST}"
      OVERWRITEPROTOCOL: "https"
      OVERWRITECLIURL: "${OVERWRITECLIURL}"
    volumes:
      - ./data:/var/www/html
      - ./hooks-post-upgrade:/docker-entrypoint-hooks.d/post-upgrade
    networks:
      - nextclouddb-net
      - nextcloud-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

  nextclouddb:
    image: mariadb:10.6
    container_name: nextclouddb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - nextclouddb-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

  nextcloudredis:
    image: redis:latest
    container_name: nextcloudredis
    networks:
      - nextcloud-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always

networks:
  nextclouddb-net:
  nextcloud-net:
    attachable: true
